backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Creado {{collection}} “{{slug}}”'
    update: 'Actualizado {{collection}} “{{slug}}”'
    delete: 'Eliminado {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Subido “{{path}}”'
    deleteMedia: '[skip ci] Eliminado “{{path}}”'

media_folder: 'public/images/uploads' # Folder where user uploaded files should go
public_folder: '/images/uploads'

collections: # A list of collections the CMS should be able to edit
  - name: 'post' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Recetas' # Used in the UI, ie.: "New Post"
    folder: 'src/pages/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "$/layouts/post.astro"}
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'text' }
      - { label: 'Cuerpo', name: 'body', widget: 'markdown' }
      - { label: 'Etiquetas', name: 'tags', widget: 'list' }
      - { label: 'Categoría', name: 'category', widget: 'hidden', default: 'blog' }
      - { label: 'Autor', name: 'author', widget: 'string' }
      - { label: 'Usuario Twitter', name: 'authorTwitter', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'date' }
      - { label: 'Imagen', name: 'image', widget: 'image', required: false, format: 'DD-MM-YYYY'}
      
  - name: 'draf' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Borradores' # Used in the UI, ie.: "New Post"
    folder: 'src/pages/drafts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "$/layouts/post.astro"}
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - { label: 'Descripción', name: 'description', widget: 'text' }
      - { label: 'Cuerpo', name: 'body', widget: 'markdown' }
      - { label: 'Etiquetas', name: 'tags', widget: 'list' }
      - { label: 'Categoría', name: 'category', widget: 'hidden', default: 'blog' }
      - { label: 'Autor', name: 'author', widget: 'string' }
      - { label: 'Usuario Twitter', name: 'authorTwitter', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'date', required: false, format: 'DD-MM-YYYY' }
      - { label: 'Imagen', name: 'image', widget: 'image', required: false}
