name: Publish drafts

on:
  push:
    branches: [master]
  schedule:
    - cron: "30 */4 * * *"
  workflow_dispatch:

jobs:
  publish-drafts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: SSG Publish Drafts
        uses: one-aalam/github-action-astro-publish-drafts@v0.1-beta
        with:
          github_token: $\{{ secrets.GITHUB_TOKEN }}
          github_actor: soker90
          github_repository: soker90/cooking-blog
          site_drafts_dir: "src/pages/drafts"
          branch: "master"
