
name: Search data

# Refresh search data
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  refresh-search:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16'
      - name: Install dependencies
        run: npm i
      - name: refresh
        run: npm run postbuild
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Refresh search data
          file_pattern: 'public/search-index.json'
  
